DoAn_ShopOnline/Areas/Admin/Controllers/HoaDonAdminController.cs
using DoAn_ShopOnline.Models.BUS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace DoAn_ShopOnline.Areas.Admin.Controllers
{
    public class HoaDonAdminController : Controller
    {
        // GET: Admin/HoaDonAdmin
        public ActionResult Index(int page = 1, int pagesize = 3)
        {
            var ds = ThanhToanBUS.DanhSachHoaDon().ToPagedList(page, pagesize);
            return View(ds);
        }
        [HttpGet]
        public ActionResult CapNhat(long mahoadon ,int trangthai)
        {
           try
           {
                ThanhToanBUS.SuaDonHang(mahoadon, trangthai);
                return RedirectToAction("../HoaDonAdmin/index");
           }
          catch
            {
                return RedirectToAction("../HoaDonAdmin/index");
           }
            
        }

        public JsonResult ChiTiet(long id)
        {
            var chitiethoadon = ThanhToanBUS.ChiTietHoaDon(id);

            return Json(new
            {
                data = chitiethoadon
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

DoAn_ShopOnline/Areas/Admin/Views/HoaDonAdmin/Index.cshtml
@model PagedList.IPagedList<ShopOnlineConnection.HoaDon>
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<style>
    table {
        border-collapse: collapse;
        width: 100%;
        margin: auto;
    }

    th, td {
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #5d5e63;
    }

    th {
        background-color: #2a9fd6;
        color: white;
    }
</style>
<h2>Quản Lý Hóa Đơn</h2>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
<table>
    <tr>
        <th>ID</th>
        <th>Ngày Tạo</th>
        <th>Người nhận</th>
        <th>Sô điện thoại</th>
        <th>Địa Chỉ</th>
        <th>Tổng Tiền</th>
        <th>Tình Trạng</th>
        <th colspan="3">Chức năng</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID</td>
            <td>@item.NgayTao</td>
            <td>@item.NguoiNhan</td>
            <td>@item.SDT</td>
            <td>@item.DiaChi</td>
            <td>@item.TongTien</td>
            @*Trạng thái  0:chưa duyệt , 1 : đang giao , 2 : đã giao, 3 : đã hủy ()*@ 
            @switch(item.TrangThai)
                {
                    case 0: <td>Chưa duyệt</td> 
                    break;
                case 1:<td>Đang giao</td>
                    break;
                case 2:<td>Đã giao</td>
                    break;
                case 3: <td>Đã hủy</td>
                    break;
            }
            @*@Html.Partial("_ChiTietHoaDon", DoAn_ShopOnline.Models.BUS.ThanhToanBUS.ChiTietHoaDon(item.ID))*@
           <td><a href="#" data-id="@item.ID" class="btn-images"></a></td>

            <td>
                <input type="hidden" value="@item.ID" id="mahoadon"/>
                <a href="#" data-id="@item.ID" class="btn-chitiet"><span class="glyphicon glyphicon-folder-open"> CTDH</span></a>

            </td>

            <td colspan="2" >
            <form action="@Url.Action("CapNhat","HoaDonAdmin")" method="get">
                <input type="hidden" name="mahoadon" value="@item.ID" />
                <select name="trangthai" class="btn btn-info">
                    <option  value="0" selected hidden >Vui lòng chọn</option>
                    <option value="0">Chưa duyệt</option>
                    <option value="1">Đang giao</option>
                    <option value="2">Đã giao</option>
                    <option value="3">Đã hủy</option>
                </select>
                 <input type="submit" class="btn btn-info" value="Sửa"/>
            </form>
            </td>
        </tr>
    }

</table>

<div class="modal fade" id="ChiTietModal" role="dialog" >
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content" style="width:100%">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Chi Tiết Hóa Đơn</h4>
            </div>
            <div class="modal-body">
                <div style="float:left" class="col-md-12">
                    <span class=col-md-2>Mã Hóa Đơn</span>
                    <span class=col-md-2>Mã Sản Phẩm </span>
                    <span class=col-md-2>Tên Sản Phẩm</span>
                    <span class=col-md-2>Số Lượng</span>
                    <span class=col-md-2>Giá</span>
                    <span class=col-md-2>Tổng Tiền</span>
                </div>
                <div id="ListChiTiet">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>